export interface SeedCareerData {
  title: string;
  description: string;
  requiredSkills: string[];
  recommendedInterests: string[];
  averageSalary: string;
  futureDemand: string;
  growthRate: number;
  roadmap: string[];
}

export const SEED_CAREERS: SeedCareerData[] = [
  {
    title: 'AI Engineer',
    description: 'Design and build artificial intelligence systems including machine learning models, neural networks, NLP solutions, and computer vision applications. Work on cutting-edge AI technologies to solve complex real-world problems across industries.',
    requiredSkills: ['Programming', 'Mathematics', 'Problem Solving', 'Machine Learning', 'Deep Learning', 'Python'],
    recommendedInterests: ['AI', 'Data Science', 'Machine Learning'],
    averageSalary: '$150,000 - $220,000',
    futureDemand: '+34% over 5 years',
    growthRate: 34,
    roadmap: [
      'Learn Python and data structures',
      'Master linear algebra, calculus, and statistics',
      'Study machine learning fundamentals',
      'Build end-to-end ML projects',
      'Learn deep learning frameworks (TensorFlow, PyTorch)',
      'Deploy models to production',
      'Specialize in NLP, computer vision, or reinforcement learning',
    ],
  },
  {
    title: 'Data Scientist',
    description: 'Analyze large datasets to extract actionable insights using statistical methods, machine learning, and data visualization. Drive data-informed business decisions and build predictive models.',
    requiredSkills: ['Mathematics', 'Programming', 'Problem Solving', 'Statistics', 'Data Visualization', 'SQL'],
    recommendedInterests: ['Data Science', 'AI', 'Business'],
    averageSalary: '$130,000 - $190,000',
    futureDemand: '+28% over 5 years',
    growthRate: 28,
    roadmap: [
      'Learn Python and SQL',
      'Master statistics and probability',
      'Learn Pandas, NumPy, and data manipulation',
      'Study machine learning algorithms',
      'Practice on Kaggle competitions',
      'Build data pipeline and ETL projects',
      'Learn big data tools (Spark, Hadoop)',
    ],
  },
  {
    title: 'Cybersecurity Analyst',
    description: 'Protect organizational systems and data from cyber threats. Monitor networks, perform vulnerability assessments, implement security measures, and respond to incidents.',
    requiredSkills: ['Programming', 'Problem Solving', 'Communication', 'Network Security', 'Ethical Hacking', 'Linux'],
    recommendedInterests: ['Cybersecurity', 'Networking'],
    averageSalary: '$120,000 - $180,000',
    futureDemand: '+31% over 5 years',
    growthRate: 31,
    roadmap: [
      'Learn networking fundamentals (TCP/IP, DNS)',
      'Study security frameworks and compliance',
      'Learn Python for security automation',
      'Get CompTIA Security+ certification',
      'Practice on CTF platforms (HackTheBox)',
      'Specialize in cloud security or penetration testing',
    ],
  },
  {
    title: 'Full Stack Developer',
    description: 'Build and maintain web applications across frontend and backend. Work with modern frameworks, databases, APIs, and cloud services to create seamless user experiences at scale.',
    requiredSkills: ['Programming', 'Design', 'Problem Solving', 'JavaScript', 'Databases', 'UI/UX'],
    recommendedInterests: ['Web Development', 'Design', 'Business'],
    averageSalary: '$110,000 - $170,000',
    futureDemand: '+20% over 5 years',
    growthRate: 20,
    roadmap: [
      'Learn HTML, CSS, and JavaScript fundamentals',
      'Master React, Next.js, or Vue.js',
      'Learn Node.js and Express/NestJS for backend',
      'Study databases (PostgreSQL, MongoDB)',
      'Build full-stack projects',
      'Learn cloud deployment (AWS, Vercel)',
      'Understand CI/CD and testing',
    ],
  },
  {
    title: 'Product Manager',
    description: 'Define product vision, strategy, and roadmap. Work cross-functionally with engineering, design, marketing, and business teams to deliver products that solve user needs and drive growth.',
    requiredSkills: ['Leadership', 'Communication', 'Problem Solving', 'Strategic Thinking', 'User Research', 'Data Analysis'],
    recommendedInterests: ['Business', 'Web Development', 'Data Science'],
    averageSalary: '$130,000 - $200,000',
    futureDemand: '+18% over 5 years',
    growthRate: 18,
    roadmap: [
      'Learn product management fundamentals',
      'Master user research and usability testing',
      'Study agile and Scrum methodologies',
      'Build product case studies',
      'Learn data-driven decision making',
      'Develop domain expertise in target industry',
      'Build a portfolio of shipped products',
    ],
  },
  {
    title: 'Network Engineer',
    description: 'Design, implement, and manage computer networks. Ensure network reliability, security, and performance for enterprise organizations. Work with cloud networking and SDN technologies.',
    requiredSkills: ['Programming', 'Problem Solving', 'Communication', 'Network Protocols', 'Cloud Networking', 'Linux'],
    recommendedInterests: ['Networking', 'Cybersecurity'],
    averageSalary: '$100,000 - $160,000',
    futureDemand: '+12% over 5 years',
    growthRate: 12,
    roadmap: [
      'Learn networking fundamentals (TCP/IP, DNS, DHCP)',
      'Get CCNA or equivalent certification',
      'Learn Python for network automation',
      'Study cloud networking (AWS VPC, Azure)',
      'Practice network troubleshooting',
      'Learn SDN and network virtualization',
    ],
  },
  {
    title: 'Game Developer',
    description: 'Design and develop video games across platforms. Create gameplay mechanics, graphics, audio systems, and interactive storytelling experiences using game engines.',
    requiredSkills: ['Programming', 'Creativity', 'Design', 'Game Engines', '3D Graphics', 'C++'],
    recommendedInterests: ['Gaming', 'Design', 'AI'],
    averageSalary: '$90,000 - $150,000',
    futureDemand: '+15% over 5 years',
    growthRate: 15,
    roadmap: [
      'Learn C++ or C# programming',
      'Study game engines (Unity or Unreal Engine)',
      'Learn 3D modeling basics (Blender)',
      'Build small games from scratch',
      'Study game physics and rendering',
      'Participate in game jams',
      'Build a portfolio of released games',
    ],
  },
  {
    title: 'Cloud Engineer',
    description: 'Design, implement, and manage cloud infrastructure on AWS, Azure, or GCP. Build scalable, resilient, and cost-effective cloud architectures for modern applications.',
    requiredSkills: ['Programming', 'Problem Solving', 'Cloud Networking', 'Linux', 'DevOps', 'Databases'],
    recommendedInterests: ['Web Development', 'Networking', 'Data Science'],
    averageSalary: '$140,000 - $200,000',
    futureDemand: '+25% over 5 years',
    growthRate: 25,
    roadmap: [
      'Learn Linux system administration',
      'Master one cloud provider (AWS/Azure/GCP)',
      'Learn infrastructure as code (Terraform)',
      'Study containerization (Docker, Kubernetes)',
      'Build CI/CD pipelines',
      'Learn monitoring and observability',
      'Get cloud certifications (AWS Solutions Architect)',
    ],
  },
  {
    title: 'DevOps Engineer',
    description: 'Bridge development and operations by automating infrastructure, streamlining CI/CD pipelines, managing containerized deployments, and ensuring system reliability and scalability.',
    requiredSkills: ['Programming', 'Problem Solving', 'Linux', 'DevOps', 'Cloud Networking', 'Communication'],
    recommendedInterests: ['Web Development', 'Networking', 'Cybersecurity'],
    averageSalary: '$135,000 - $195,000',
    futureDemand: '+22% over 5 years',
    growthRate: 22,
    roadmap: [
      'Learn Linux and shell scripting',
      'Master version control (Git)',
      'Learn CI/CD tools (Jenkins, GitHub Actions)',
      'Study containerization (Docker)',
      'Learn orchestration (Kubernetes)',
      'Master infrastructure as code (Terraform, Ansible)',
      'Implement monitoring (Prometheus, Grafana)',
    ],
  },
  {
    title: 'UI/UX Designer',
    description: 'Design intuitive and visually appealing user interfaces. Conduct user research, create wireframes and prototypes, and collaborate with developers to deliver exceptional user experiences.',
    requiredSkills: ['Design', 'Creativity', 'Communication', 'UI/UX', 'Problem Solving', 'User Research'],
    recommendedInterests: ['Design', 'Web Development', 'Gaming'],
    averageSalary: '$95,000 - $155,000',
    futureDemand: '+16% over 5 years',
    growthRate: 16,
    roadmap: [
      'Learn design principles and color theory',
      'Master Figma or Adobe XD',
      'Study user research methodologies',
      'Build a portfolio of case studies',
      'Learn HTML/CSS for better developer collaboration',
      'Study accessibility and inclusive design',
      'Specialize in product or interaction design',
    ],
  },
];
